<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [8]:
%%sql
select *
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [ ]:
%%sql
SELECT quantity,
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [19]:
%%sql
SELECT *
FROM information_schema.columns

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2046 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,pg_catalog,pg_attribute,attinhcount,21,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,pg_catalog,pg_stat_gssapi,pid,1,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
2,contoso_100k,pg_catalog,pg_stat_gssapi,gss_authenticated,2,None,YES,boolean,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
3,contoso_100k,pg_catalog,pg_attribute,attcollation,22,None,NO,oid,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,pg_catalog,pg_stat_gssapi,encrypted,4,None,YES,boolean,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2041,contoso_100k,pg_catalog,pg_type,typdefault,31,None,YES,text,NaN,1073741824.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2042,contoso_100k,pg_catalog,pg_statistic_ext,stxname,3,None,NO,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2043,contoso_100k,pg_catalog,pg_statio_user_tables,relname,3,None,YES,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
2044,contoso_100k,pg_catalog,pg_statio_user_tables,schemaname,2,None,YES,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
2045,contoso_100k,pg_catalog,pg_statio_sys_tables,relname,3,None,YES,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO

In [27]:
%%sql
select *,  quantity*netprice/exchangerate as net_revenue
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate,net_revenue
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64,154.26
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64,1028.42
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00,108.75
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00,1146.75
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00,950.25
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00,1302.91
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00,58.73
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00,224.98
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16,196.10
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16,431.19

In [11]:
%%sql
select *
from product

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2517 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2513,505026,Contoso Bluetooth Active Headphones L15 Red,"Contoso, Ltd",Contoso,Red,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2513,2514,505027,Contoso Bluetooth Active Headphones L15 White,"Contoso, Ltd",Contoso,White,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2514,2515,505028,Contoso In-Line Coupler E180 White,"Contoso, Ltd",Contoso,White,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2515,2516,505029,Contoso In-Line Coupler E180 Black,"Contoso, Ltd",Contoso,Black,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2516,2517,505030,Contoso In-Line Coupler E180 Silver,"Contoso, Ltd",Contoso,Silver,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories

In [12]:
%%sql
select *
from date

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3653 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3648,2024-12-27,20241227,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Friday,Fri,6,1,2507
3649,2024-12-28,20241228,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Saturday,Sat,7,0,2507
3650,2024-12-29,20241229,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Sunday,Sun,1,0,2507
3651,2024-12-30,20241230,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Monday,Mon,2,1,2508
3652,2024-12-31,20241231,2024,Q4-2024,8100,Q4,December 2024,Dec 2024,24300,December,Dec,12,Tuesday,Tue,3,1,2509

In [13]:
%%sql
select *
from customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

104990 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104985,2099639,580,1988-12-05,2016-07-02,North America,male,Mr.,Miroslav,M,Slach,...,62550,US,United States,1945-04-30,75,Placement specialist,Strength Gurus,2006 Suzuki Sea Forenza Wagon,39.59,-88.89
104986,2099656,567,1997-04-07,2043-01-10,North America,male,Mr.,Wilfredo,A,Lozada,...,35404,US,United States,1945-08-24,75,Industrial economist,Williams Bros.,2012 Mercedes-Benz E,33.17,-87.51
104987,2099697,570,2003-03-17,2043-03-02,North America,male,Mr.,Phillipp,S,Maier,...,93401,US,United States,1966-12-08,54,Mail sorter,Excella,2010 Subaru Tribeca,35.23,-120.59
104988,2099711,591,1980-08-26,2043-04-27,North America,female,Mrs.,Katerina,M,Pavlícková,...,39401,US,United States,1941-01-01,80,Light truck driver,Lawnscape Garden Maintenance,2006 Bentley Arnage,31.26,-89.19
104989,2099743,591,1985-04-01,2045-12-25,North America,female,Ms.,Luciana,N,Almonte,...,39095,US,United States,2000-02-22,21,Cabinetmaker,Frank's Nursery & Crafts,1995 Subaru Vivio,33.06,-90.02

In [15]:
%%sql
select *
from currencyexchange

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

91325 rows affected.

             date fromcurrency tocurrency  exchange
0      2015-01-01          AUD        AUD      1.00
1      2015-01-01          AUD        CAD      0.95
2      2015-01-01          AUD        EUR      0.67
3      2015-01-01          AUD        GBP      0.53
4      2015-01-01          AUD        USD      0.82
...           ...          ...        ...       ...
91320  2024-12-31          USD        AUD      1.55
91321  2024-12-31          USD        CAD      1.35
91322  2024-12-31          USD        EUR      0.92
91323  2024-12-31          USD        GBP      0.78
91324  2024-12-31          USD        USD      1.00

[91325 rows x 4 columns]

In [16]:
%%sql
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store